/**
 * THE KATHA - Eka Vimshathi Patra (21 Sacred Leaves) Data Model
 *
 * Lord Ganesha Vinayaka Chavithi Puja 21 Sacred Leaves.
 * Distribution:
 * - Companion 1 (Chintu): 6 types
 * - Companion 2 (Bhavani): 6 types
 * - Companion 3 (Varun): 6 types
 * - Ramu + Companion 4 (Deepa): 3 types (Crucially includes DURVA GRASS!)
 * Total: 21 unique types
 */

import { CharacterId } from './game';

export interface SacredLeafInfo {
  id: string;
  name: string;
  sanskritName: string;
  teluguName: string;
  deityMantraSnippet: string; // Sacred offering reference
  assignedCollector: CharacterId;
  collectorName: string;
  collectorGroup: 'chintu' | 'bhavani' | 'varun' | 'ramu_deepa';
  plantColor: string;
  flowerColor?: string;
  plantStyle: 'durva' | 'basil' | 'broad_leaf' | 'shrub' | 'flowering' | 'fern' | 'slender';
  relativePos: { x: number; z: number }; // Offset from Forest Clearing Center (26, 0, -42)
  isCollected: boolean;
  isBeingCollected?: boolean;
  collectedBy?: string;
}

export const SACRED_21_LEAVES: SacredLeafInfo[] = [
  // --- COMPANION 1: CHINTU (6 types) ---
  {
    id: 'machi',
    name: 'Machi Leaf',
    sanskritName: 'Machipatram',
    teluguName: 'మాచిపత్రం (మరువం)',
    deityMantraSnippet: 'Om Sumukhaya Namah - Machipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#4ade80',
    flowerColor: '#fef08a',
    plantStyle: 'shrub',
    relativePos: { x: -4.5, z: -3.2 },
    isCollected: false,
  },
  {
    id: 'brihati',
    name: 'Brihati Leaf',
    sanskritName: 'Brihatipatram',
    teluguName: 'బృహతీపత్రం (వాకుడాకు)',
    deityMantraSnippet: 'Om Ganadhipaya Namah - Brihatipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#22c55e',
    flowerColor: '#c084fc',
    plantStyle: 'flowering',
    relativePos: { x: -6.2, z: -1.0 },
    isCollected: false,
  },
  {
    id: 'bilva',
    name: 'Bilva (Bael) Leaf',
    sanskritName: 'Bilvapatram',
    teluguName: 'బిల్వపత్రం (మారేడు)',
    deityMantraSnippet: 'Om Umaputraya Namah - Bilvapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#15803d',
    plantStyle: 'broad_leaf',
    relativePos: { x: -3.8, z: 2.8 },
    isCollected: false,
  },
  {
    id: 'badari',
    name: 'Badari (Jujube) Leaf',
    sanskritName: 'Badaripatram',
    teluguName: 'బదరీపత్రం (రేగు)',
    deityMantraSnippet: 'Om Lambodaraya Namah - Badaripatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#16a34a',
    flowerColor: '#facc15',
    plantStyle: 'shrub',
    relativePos: { x: -5.8, z: 4.2 },
    isCollected: false,
  },
  {
    id: 'karaveera',
    name: 'Karaveera Leaf',
    sanskritName: 'Karaveerapatram',
    teluguName: 'కరవీరపత్రం (గన్నేరు)',
    deityMantraSnippet: 'Om Harisunave Namah - Karaveerapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#166534',
    flowerColor: '#fb7185', // Pink Oleander flower
    plantStyle: 'flowering',
    relativePos: { x: -2.5, z: 5.5 },
    isCollected: false,
  },
  {
    id: 'tulasi',
    name: 'Tulasi (Holy Basil)',
    sanskritName: 'Tulasipatram',
    teluguName: 'తులసీపత్రం (తులసి)',
    deityMantraSnippet: 'Om Gajananaya Namah - Tulasipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_1,
    collectorName: 'Chintu',
    collectorGroup: 'chintu',
    plantColor: '#15803d',
    flowerColor: '#818cf8',
    plantStyle: 'basil',
    relativePos: { x: -4.0, z: -5.5 },
    isCollected: false,
  },

  // --- COMPANION 2: BHAVANI (6 types) ---
  {
    id: 'parijata',
    name: 'Parijata Leaf',
    sanskritName: 'Parijatapatram',
    teluguName: 'పారిజాతపత్రం (పారిజాతం)',
    deityMantraSnippet: 'Om Vakratundaya Namah - Parijatapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#22c55e',
    flowerColor: '#ffffff', // White with orange center
    plantStyle: 'flowering',
    relativePos: { x: 3.5, z: -5.2 },
    isCollected: false,
  },
  {
    id: 'shami',
    name: 'Shami (Jammi) Leaf',
    sanskritName: 'Shamipatram',
    teluguName: 'శమీపత్రం (జమ్మి)',
    deityMantraSnippet: 'Om Guhagrajaya Namah - Shamipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#166534',
    flowerColor: '#fde047',
    plantStyle: 'slender',
    relativePos: { x: 5.8, z: -3.0 },
    isCollected: false,
  },
  {
    id: 'apamarga',
    name: 'Apamarga Leaf',
    sanskritName: 'Apamargapatram',
    teluguName: 'అపామార్గపత్రం (ఉత్తరేణి)',
    deityMantraSnippet: 'Om Ekadantaya Namah - Apamargapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#4ade80',
    plantStyle: 'shrub',
    relativePos: { x: 6.5, z: -0.5 },
    isCollected: false,
  },
  {
    id: 'maruvaka',
    name: 'Maruvaka Leaf',
    sanskritName: 'Maruvakapatram',
    teluguName: 'మరువకపత్రం (మరువం)',
    deityMantraSnippet: 'Om Vighnarajaya Namah - Maruvakapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#86efac',
    plantStyle: 'basil',
    relativePos: { x: 5.2, z: 2.6 },
    isCollected: false,
  },
  {
    id: 'agastya',
    name: 'Agastya Leaf',
    sanskritName: 'Agastyapatram',
    teluguName: 'అగస్త్యపత్రం (అవిసె)',
    deityMantraSnippet: 'Om Sarveshvaraya Namah - Agastyapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#15803d',
    plantStyle: 'broad_leaf',
    relativePos: { x: 4.2, z: 5.2 },
    isCollected: false,
  },
  {
    id: 'ashwattha',
    name: 'Ashwattha (Sacred Fig)',
    sanskritName: 'Ashwatthapatram',
    teluguName: 'అశ్వత్థపత్రం (రావి)',
    deityMantraSnippet: 'Om Sarvasiddhipradaya Namah - Ashwatthapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_2,
    collectorName: 'Bhavani',
    collectorGroup: 'bhavani',
    plantColor: '#16a34a',
    plantStyle: 'broad_leaf',
    relativePos: { x: 6.0, z: 4.8 },
    isCollected: false,
  },

  // --- COMPANION 3: VARUN (6 types) ---
  {
    id: 'dhattura',
    name: 'Dhattura Leaf',
    sanskritName: 'Dhatturapatram',
    teluguName: 'ధత్తూరపత్రం (ఉమ్మెత్త)',
    deityMantraSnippet: 'Om Vinayakaya Namah - Dhatturapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#15803d',
    flowerColor: '#e9d5ff', // Purple bell flower
    plantStyle: 'flowering',
    relativePos: { x: -1.2, z: -6.5 },
    isCollected: false,
  },
  {
    id: 'arjuna',
    name: 'Arjuna Leaf',
    sanskritName: 'Arjunapatram',
    teluguName: 'అర్జునపత్రం (తెల్లమద్ది)',
    deityMantraSnippet: 'Om Kapilaya Namah - Arjunapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#166534',
    plantStyle: 'broad_leaf',
    relativePos: { x: 1.5, z: -6.8 },
    isCollected: false,
  },
  {
    id: 'arka',
    name: 'Arka Leaf',
    sanskritName: 'Arkapatram',
    teluguName: 'అర్కపత్రం (జిల్లేడు)',
    deityMantraSnippet: 'Om Vikataya Namah - Arkapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#86efac',
    flowerColor: '#c084fc',
    plantStyle: 'flowering',
    relativePos: { x: -1.0, z: 6.8 },
    isCollected: false,
  },
  {
    id: 'devadaru',
    name: 'Devadaru Leaf',
    sanskritName: 'Devadarupatram',
    teluguName: 'దేవదారుపత్రం (దేవదారు)',
    deityMantraSnippet: 'Om Ishaputraya Namah - Devadarupatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#14532d',
    plantStyle: 'slender',
    relativePos: { x: 1.2, z: 7.0 },
    isCollected: false,
  },
  {
    id: 'sindhuvara',
    name: 'Sindhuvara Leaf',
    sanskritName: 'Sindhuvarapatram',
    teluguName: 'సింధువారపత్రం (వావిలాకు)',
    deityMantraSnippet: 'Om Bhalachandraya Namah - Sindhuvarapatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#22c55e',
    flowerColor: '#a78bfa',
    plantStyle: 'flowering',
    relativePos: { x: -6.8, z: 1.5 },
    isCollected: false,
  },
  {
    id: 'gandaki',
    name: 'Gandaki Leaf',
    sanskritName: 'Gandakipatram',
    teluguName: 'గండకీపత్రం (కుసుమ)',
    deityMantraSnippet: 'Om Herambaya Namah - Gandakipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_3,
    collectorName: 'Varun',
    collectorGroup: 'varun',
    plantColor: '#16a34a',
    plantStyle: 'shrub',
    relativePos: { x: 6.8, z: -5.0 },
    isCollected: false,
  },

  // --- RAMU + COMPANION 4: DEEPA (3 types - MANDATORY DURVA GRASS) ---
  {
    id: 'durva',
    name: 'Durva Grass',
    sanskritName: 'Durvayugmam',
    teluguName: 'దూర్వాయుగ్మం (గరిక)',
    deityMantraSnippet: 'Om Gananathaya Namah - Durvayugmam Samarpayami (Supreme Offering)',
    assignedCollector: CharacterId.RAMU,
    collectorName: 'Ramu & Deepa',
    collectorGroup: 'ramu_deepa',
    plantColor: '#4ade80',
    flowerColor: '#facc15',
    plantStyle: 'durva',
    relativePos: { x: -0.2, z: -3.6 }, // Positioned right near central path for Ramu!
    isCollected: false,
  },
  {
    id: 'ketaki',
    name: 'Ketaki Leaf',
    sanskritName: 'Ketakipatram',
    teluguName: 'కేతకీపత్రం (మొగిలి)',
    deityMantraSnippet: 'Om Skandapurvajaya Namah - Ketakipatram Samarpayami',
    assignedCollector: CharacterId.COMPANION_4,
    collectorName: 'Ramu & Deepa',
    collectorGroup: 'ramu_deepa',
    plantColor: '#16a34a',
    flowerColor: '#fef08a',
    plantStyle: 'slender',
    relativePos: { x: -2.8, z: -1.8 },
    isCollected: false,
  },
  {
    id: 'mallika',
    name: 'Mallika (Jasmine) Leaf',
    sanskritName: 'Mallikapatram',
    teluguName: 'మల్లికాపత్రం (మల్లె)',
    deityMantraSnippet: 'Om Surpanakarnaya Namah - Mallikapatram Samarpayami',
    assignedCollector: CharacterId.RAMU,
    collectorName: 'Ramu & Deepa',
    collectorGroup: 'ramu_deepa',
    plantColor: '#15803d',
    flowerColor: '#ffffff', // Sweet fragrant white jasmine
    plantStyle: 'flowering',
    relativePos: { x: 2.6, z: -1.6 },
    isCollected: false,
  },
];
